### ISSUE TITLE
Polyfill instead of fallback

### ISSUE THREAD

**Issue by fregante** [alex499/postcss-image-set#2]
The current implementation only sets a fallback, making `image-set()` useless in [40% of the browsers](http://caniuse.com/#feat=css-image-set). This could be fixed by outputting a media query instead

``` css
.foo {
    /* Input */
    background-image: image-set(url(img/test.png) 1x,
                                url(img/test-2x.png) 2x;
}
```

``` css
/* Simple output */
.foo {
    background-image: url(img/test.png);
}
@media (min-resolution: 2dppx) {
    .foo {
        background-image: url(img/test-2x.png) 2x;
    }
}
```

``` css
/* Ideal output */
.foo {
    background-image: url(img/test.png);
    background-image: image-set(url(img/test.png) 1x,
                                url(img/test-2x.png) 2x;
}
@media (min-resolution: 2dppx) {
    .foo {
        background-image: url(img/test-2x.png);

        /* we still want to leave the choice to the browser, where supported */
        background-image: image-set(url(img/test.png) 1x,
                                url(img/test-2x.png) 2x;
    }
}
```
